<style type="text/css">
    .mb_nav_active_fix{
        color: #00adef;
        font-weight: 700;
        text-transform: uppercase;
        font-size: 12px;
    }
    .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
        color: #00adef;
        background-color: #fff;
        font-weight: bold;
    }
    .nav-tabs .nav-item.show .nav-link:not(.dropdown-toggle):after, .nav-tabs .nav-link.active:not(.dropdown-toggle):after {
        color: #00adef;
        content: '';
        position: absolute;
        width: 100%;
        left: 0;
        right: 0;
        bottom: 0;
        height: 2px;
        background-color: #00adef;
    } 
 
</style>
 
<div id="e-commerce-product" class="page-layout simple tabbed">

    <!-- HEADER -->
    <div class="page-header bg-secondary text-auto row no-gutters align-items-center justify-content-between p-6">

        <div class="row no-gutters align-items-center">
            <div class="col-12 col-sm">
                <div class="logo row no-gutters align-items-start">
                    <div class="logo-icon mr-3 mt-0">
                        <i class="icon-account-plus s-8" style="color: #3c4252;"></i>
                    </div>
                    <div class="logo-text">
                        <div class="h4" style="color: #3c4252;">Add User</div>
                    </div>
                </div>
            </div>
        </div>
        

    </div>
    <!-- / HEADER -->

    <!-- CONTENT -->
    <div class="page-content">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="basic-info-tab-pane" role="tabpanel" aria-labelledby="basic-info-tab">
                <div class="card p-12">
                    <form method="post">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                       <div class="product-image m-2">
                                            <img class="w-100" src="<?php echo $_layoutParams['root_img']; ?>backgrounds/january.jpg">
                                        </div>
                                        <label class="custom-file">
                                            <input type="file" id="file" class="custom-file-input">
                                            <span class="custom-file-control"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-9">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" id="mb_userFirstName" placeholder="">
                                        <label for="mb_userFirstName" class="col-form-label">Fisrt Name</label>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" id="mb_userMiddleName" placeholder="">
                                        <label for="mb_userMiddleName" class="col-form-label">Middle Name</label>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <input type="text" class="form-control" id="mb_userLastName" placeholder="">
                                        <label for="mb_userLastName" class="col-form-label">Last Name</label>
                                    </div>
                                </div>
                                
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <div class="form-row align-items-center">
                                            <div class="col-auto">
                                                <label class="sr-only" for="inlineFormInput">Name</label>
                                                <input type="text" class="form-control mb-2 mb-sm-0" id="inlineFormInput"
                                                       placeholder="Jane Doe">
                                            </div>
                                            <div class="col-auto">
                                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                                <div class="input-group mb-2 mb-sm-0">
                                                    <div class="input-group-addon">@</div>
                                                    <input type="text" class="form-control" id="inlineFormInputGroup"
                                                           placeholder="Username" aria-describedby="passwordHelpBlock">
                                                </div>
                                            </div>
                                            <small id="passwordHelpBlock" class="form-text text-muted">
                                                Add your user account to access MacbotWeb.
                                            </small>    
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <fieldset class="form-group">
                                            <div class="row">
                                                <legend class="col-form-legend col-sm-4">User Type</legend>
                                                <div class="col-sm-8">
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="gridRadios"
                                                                   id="gridRadios1" value="option1" checked>
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Master User</span>
                                                        </label>
                                                    </div>
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="gridRadios"
                                                                   id="gridRadios2" value="option2">
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Normal User</span>
                                                        </label>
                                                    </div>
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="gridRadios"
                                                                   id="gridRadios3" value="option3">
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Read Only User</span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <ul class="nav nav-tabs" id="myTab" role="tablist" style="border-bottom: 1px solid #ddd;">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                           aria-controls="home" aria-expanded="true">Contacts</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                                           aria-controls="profile">Password</a>
                                    </li>
                                   
                                </ul>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                         <p>
                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" id="mb_Mobile" placeholder="">
                                                    <label for="mb_Mobile" class="col-form-label">Mobile Phone</label>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" id="mb_Phone" placeholder="">
                                                    <label for="mb_Phone" class="col-form-label">Work Phone</label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" id="mb_Address" placeholder="1234 Main St">
                                                <label for="mb_Address" class="col-form-label">Address</label>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" id="mb_Address2" placeholder="1234 Main St">
                                                <label for="mb_Address2" class="col-form-label">Address 2</label>
                                            </div>
                                        </p>
                                    </div>
                                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <p>
                                            <div class="form-row">
                                            <label for="inputPassword5">Password</label>
                                                <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock">
                                                <small id="passwordHelpBlock" class="form-text text-muted">
                                                    Your password must be 8-20 characters long, contain letters and numbers, and must not contain
                                                    spaces, special characters, or emoji.
                                                </small>
                                                <!--<div class="form-group col-md-6">
                                                    <input type="text" class="form-control" id="mb_userFirstName" placeholder="">
                                                    <label for="mb_userFirstName" class="col-form-label">Current Password </label>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" id="mb_userMiddleName" placeholder="">
                                                    <label for="mb_userMiddleName" class="col-form-label">New Password</label>
                                                </div>-->
                                            </div>
                                            <!--<div class="form-row">
                                                <div class="form-group col-md-12">
                                                    <input type="text" class="form-control" id="mb_userLastName" placeholder="">
                                                    <label for="mb_userLastName" class="col-form-label">New Password Confirmation</label>
                                                </div>
                                            </div>-->
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <input type="submit" name="btn_addUser" value="SAVE" type="button" class="btn btn-primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    
 

      