<style type="text/css">
    .alert-warning{
        /*border-color:  #e16152;
        background: #e16152;
        position: relative;
        color: #fff;
        text-transform: uppercase;
        text-align: center;
        padding: 1.25em 3.75em 1.25em 1.25em;
        fill: #fff;
        -webkit-box-flex: 1;
        -ms-flex: auto 0 0;
        flex: auto 0 0;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        width: 100%;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        overflow: hidden;*/
        border-color: #e16152;
        background: #e16152;
        position: relative;
        color: #fff;
        text-transform: uppercase;
        padding: 1.25em 1.75em 0.25em 2.25em;
        fill: #fff;
        -ms-flex: auto 0 0;
        display: -ms-flexbox;
        width: 100%;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        overflow: hidden;
        border-radius: 0px;
        box-shadow: none;
        margin-bottom: 0px;
    }
</style>
    <!-- CONTENT -->
    <div class="page-content">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="basic-info-tab-pane" role="tabpanel" aria-labelledby="basic-info-tab">
                <div class="card p-12">
                    <form name="AddUserForm" method="post" action="">
                    <input type="hidden" value="1" name="send">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                       <div class="product-image m-2">
                                            <img class="w-100" src="<?php echo $_layoutParams['root_img']; ?>avatars/profile.jpg">
                                        </div>
                                        <label class="custom-file">
                                            <input type="file" id="file" class="custom-file-input">
                                            <span class="custom-file-control"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-9">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" name="mb_FirstName" id="mb_FirstName" placeholder="" value="<?php if(isset($this->datos)) echo $this->datos['mb_FirstName'];  ?>">
                                        <label for="mb_FirstName" class="col-form-label mb_input">
                                        <i class="icon s-4 icon-account"></i> Fisrt Name
                                    </label>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" name="mb_MiddleName" id="mb_MiddleName" placeholder=""  value="<?php if(isset($this->datos)) echo $this->datos['mb_MiddleName'];  ?>">
                                        <label for="mb_MiddleName" class="col-form-label mb_input"><i class="icon s-4 icon-account"></i> Middle Name
                                        </label>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <input type="text" class="form-control" name="mb_LastName" id="mb_LastName" placeholder="" value="<?php if(isset($this->datos)) echo $this->datos['mb_LastName'];  ?>">
                                        <label for="mb_LastName" class="col-form-label mb_input"><i class="icon s-4 icon-account"></i> Last Name</label>
                                    </div>
                                </div>
                                
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label class="sr-only" for="mb_User_1">Name</label>
                                                <input type="text" class="form-control mb-2 mb-sm-0" name="mb_User_1" id="mb_User_1"
                                                       placeholder="Jane Doe" value="<?php if(isset($this->datos)) echo $this->datos['mb_User_1'];  ?>">
                                           </div>
                                           <div class="form-group col-md-6">
                                                <label class="sr-only" for="mb_User_2">Username</label>
                                                <div class="input-group mb-2 mb-sm-0">
                                                    <div class="input-group-addon">@</div>
                                                    <input type="text" class="form-control" name="mb_User_2" id="mb_User_2"
                                                           placeholder="Username" aria-describedby="passwordHelpBlock" value="<?php if(isset($this->datos)) echo $this->datos['mb_User_2'];  ?>">
                                                </div>
                                            </div>
                                            <small id="passwordHelpBlock" class="form-text text-muted mb-fixed-small-user">
                                                Add your user account to access MacbotWeb.
                                            </small>    
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <fieldset class="form-group">
                                            <div class="row">
                                                <legend class="col-form-legend col-sm-4">User Type</legend>
                                                <div class="col-sm-8">
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="mb_rolUser"
                                                                   id="gridRadios1" value="2" checked>
                                                            
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Master User</span>
                                                        </label>
                                                    </div>
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="mb_rolUser"
                                                                   id="gridRadios2" value="3">
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Normal User</span>
                                                        </label>

                                                    </div>
                                                    <div class="form-check">
                                                        <label class="form-check-label">
                                                            <input class="form-check-input" type="radio" name="mb_rolUser"
                                                                   id="gridRadios3" value="4">
                                                            <span class="radio-icon"></span>
                                                            <span class="form-check-description">Read Only User</span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <ul class="nav nav-tabs" id="myTab" role="tablist" style="border-bottom: 1px solid #ddd;">
                                    <li class="nav-item">
                                        <a class="nav-link mb-link-uppercase active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                           aria-controls="home" aria-expanded="true">contacts</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link mb-link-uppercase" id="profile-tab" data-toggle="tab" href="#location" role="tab"
                                           aria-controls="location">location</a>
                                    </li>
                                   <li class="nav-item">
                                        <a class="nav-link mb-link-uppercase" id="profile-tab" data-toggle="tab" href="#password" role="tab"
                                           aria-controls="password">password 
                                           <!--<i class="icon s-5 icon-information" data-toggle="tooltip" data-placement="top" title="Si modifica la contraseña se actualizara"></i>-->
                                        </a>
                                    </li>
                                </ul>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                         <p>
                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" name="mb_Mobile" id="mb_Mobile" placeholder="" value="<?php if(isset($this->datos)) echo $this->datos['mb_Mobile'];  ?>">
                                                    <label for="mb_Mobile" class="col-form-label mb_input"><i class="icon s-4 icon-cellphone-android"></i> Mobile Phone
                                                    </label>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" name="mb_Phone" id="mb_Phone" placeholder="" value="<?php if(isset($this->datos)) echo $this->datos['mb_Phone'];  ?>">
                                                    <label for="mb_Phone" class="col-form-label mb_input"><i class="icon s-4 icon-cellphone-basic"></i> Work Phone</label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="mb_Address" id="mb_Address" placeholder="1234 Main St" value="<?php if(isset($this->datos)) echo $this->datos['mb_Address'];  ?>">
                                                <label for="mb_Address" class="col-form-label mb_input"><i class="icon s-4 icon-home-variant"></i> Address</label>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="mb_Address2" id="mb_Address2" placeholder="12345 Main St" value="<?php if(isset($this->datos)) echo $this->datos['mb_Address2'];  ?>">
                                                <label for="mb_Address2" class="col-form-label mb_input"><i class="icon s-4 icon-home-variant"></i> Address2</label>
                                            </div>
                                        </p>
                                    </div>
                                    <div class="tab-pane fade" id="location" role="tabpanel" aria-labelledby="home-tab">
                                         <p>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="mb_Country" id="mb_Country" placeholder="1234 Main St">
                                                <label for="mb_Country" class="col-form-label mb_input"><i class="icon s-4 icon-home-variant"></i> Country</label>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="mb_City" id="mb_City" placeholder="1234 Main St">
                                                <label for="mb_City" class="col-form-label mb_input"><i class="icon s-4 icon-home-variant"></i> City</label>
                                            </div>
                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <input type="text" class="form-control" id="mb_Region" name="mb_Region">
                                                    <label for="mb_Region" class="col-form-label">Region</label>
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <input type="text" class="form-control" id="mb_State" name="mb_State">
                                                    <label for="mb_State" class="col-form-label">State</label>
                                                </div>
                                                <div class="form-group col-md-2">
                                                    <input type="text" class="form-control" id="mb_PostalCode" name="mb_PostalCode">
                                                    <label for="mb_PostalCode" class="col-form-label">Postal code</label>
                                                </div>
                                            </div>
                                        </p>
                                    </div>
                                    <div class="tab-pane fade" id="password" role="tabpanel" aria-labelledby="profile-tab">
                                        <p>
                                            <div class="form-row">
                                            <small id="passwordHelpBlock" class="form-text text-muted">
                                                    Your password must be 8-20 characters long, contain letters and numbers, and must not contain
                                                    spaces, special characters, or emoji.
                                                </small>
                                            <!--<label for="inputPassword5">Password</label>
                                                <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock">-->
                                                
                                                <div class="form-group col-md-6">
                                                    <input type="password" class="form-control" id="mb_Password" name="mb_Password" placeholder="">
                                                    <label for="mb_Password" class="col-form-label mb_input"><i class="icon s-4 icon-key"></i> Password </label>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input type="password" class="form-control" id="mb_PasswordConfirmation" name="mb_PasswordConfirmation" placeholder="">
                                                    <label for="mb_PasswordConfirmation" class="col-form-label mb_input"><i class="icon s-4 icon-key"></i> Password Confirmation</label>
                                                </div>
                                            </div>
                                            <!--<div class="form-row">
                                                <div class="form-group col-md-12">
                                                    <input type="text" class="form-control" id="mb_userLastName" placeholder="">
                                                    <label for="mb_userLastName" class="col-form-label">New Password Confirmation</label>
                                                </div>
                                            </div>-->
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <input type="submit"  value="SAVE" type="button" class="btn btn-primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    
 

      