<style type="text/css">
    .btn-default-bootbox {
        background-color: position: relative;
        cursor: pointer;
        background-color: transparent;
        border: none;
        border-bottom-style: solid;
        border-bottom-width: 1px;
        border-bottom-color: #bdbdbd;
        outline: 0;
        height: 4rem;
        line-height: 3rem;
        padding: 4px;
        display: block;
    }
    .btn-primary-bootbox {
        color: #fff;
        background-color: #3c4252;
        border-color: #3c4252;
        -webkit-box-shadow: 0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12);
        box-shadow: 0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12);
        -webkit-transition: -webkit-box-shadow 280ms cubic-bezier(.4,0,.2,1);
        transition: -webkit-box-shadow 280ms cubic-bezier(.4,0,.2,1);
        transition: box-shadow 280ms cubic-bezier(.4,0,.2,1);
        transition: box-shadow 280ms cubic-bezier(.4,0,.2,1),-webkit-box-shadow 280ms cubic-bezier(.4,0,.2,1);
        will-change: box-shadow;
        color: #fff!important;
        height: 4rem;
    }
    .column-title{
        text-transform: uppercase;
        font-size: 1.1rem;
        font-weight: bold;
    }
</style>
<div class="doc data-table-doc page-layout simple full-width">
    <div class="page-content row p-6">
        <div class="col-12">
            <div class="example">
                <div class="description mb_header_fix">
                    <i class="icon s-5 icon-format-list-bulleted mr-1"></i>
                    <div class="description-text">
                        <div class="mb_h3_title_widget">List of users</div>
                    </div>
                    <div class="toggle-source-preview">
                        <!--<i class="icon icon-code-tags"></i>
                        <i class="icon icon-eye-outline"></i>-->
                    </div>

                </div>
                <div class="source-preview-wrapper"><div class="preview"><div class="preview-elements" style="">
                
                <!-- SEARCH -->
                <div class="col search-wrapper px-6">
                    <div class="form-group">
                        <input type="email" class="form-control" id="products-search-input" aria-describedby="emailHelp"
                               placeholder="">
                        <label for="products-search-input" style="font-size: 14px;">Search</label>
                    </div>
                </div>
                <!-- / SEARCH -->
                <table id="listusers-data-table" class="table table-striped">
                    <thead>
                        <tr>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title"></span>
                                </div>
                            </th>
                             <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">User Type</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">First Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Middle Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Last Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Status</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Email</span>
                                </div>
                            </th>
                           
                            <th class="text-center text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Website</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title"></span>
                                </div>
                            </th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(is_array($this->usersList)): ?>
                        <?php foreach($this->usersList as $key => $val): ?>    
                        <tr>
                            <td class="text-center" style="width: 6%">
                                <?php if($val['type'] != 'MU'): ?>
                                <a href="<?php echo BASE_URL . 'setting_users/delete_setting_users/' . $val['id_user'] . '/'; ?>" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready delete_users" 
                                data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userDelete']; ?>" id="<?php echo $val['id_user'];?>">
                                    <i class="icon <?php echo $val['icon_userDelete'];?>"></i>
                                </a>
                                <?php else: ?>
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" 
                                data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userDelete']; ?>">
                                    <i class="icon <?php echo $val['icon_userDelete'];?>"></i>
                                </a>
                                <?php endif; ?>
                            </td>
                            <td class="text-center">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userType']; ?>">
                                    <i class="icon <?php echo $val['icon_userType'];?>"></i>
                                </a>
                            </td>
                            <td><?php echo $val['firstName']; ?></td>
                            <td><?php echo $val['middleName']; ?></td>
                            <td><?php echo $val['lastName']; ?></td>
                            <td class="text-center">
                                <?php echo $val['status']; ?>
                            </td>
                            <td><?php echo $val['email']; ?></td>
                            <td class="text-center" style="width: 6%;">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userWebsite']; ?>">
                                    <i class="icon <?php echo $val['icon_userWebsite'];?> icon-pointer"></i>
                                </a>
                            </td>
                            <td class="text-center" style="width: 6%;">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready">
                                    <i class="icon icon-pencil"></i>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php endif; ?>
                        
                    </tbody>
                </table>

                </div></div>
      
                </div>
            </div>
        </div>
    </div>
</div>