<div class="doc data-table-doc page-layout simple full-width">
    <div class="page-content row p-6 container">

        <div class="col-12">

            <div class="example">
                <div class="description mb_header_fix">
                    <i class="icon s-5 icon-format-list-bulleted mr-1"></i>
                    <div class="description-text">
                        <div class="mb_h3_title_widget">List of users</div>
                    </div>
                    <div class="toggle-source-preview">
                        <!--<i class="icon icon-code-tags"></i>
                        <i class="icon icon-eye-outline"></i>-->
                    </div>

                </div>
                <div class="source-preview-wrapper"><div class="preview"><div class="preview-elements" style="">
                
                <!-- SEARCH -->
                <div class="col search-wrapper px-6">
                    <div class="form-group">
                        <input type="email" class="form-control" id="products-search-input" aria-describedby="emailHelp"
                               placeholder="">
                        <label for="products-search-input" style="font-size: 14px;">Search</label>
                    </div>
                </div>
                <!-- / SEARCH -->
                <table id="listusers-data-table" class="table table-striped">
                    <thead>
                        <tr>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title"></span>
                                </div>
                            </th>
                             <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">User Type</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Nick Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">First Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Last Name</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Status</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Email</span>
                                </div>
                            </th>
                           
                            <th class="text-center text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Website</span>
                                </div>
                            </th>
                            <th class="text-center secondary-text">
                                <div class="table-header">
                                    <span class="column-title"></span>
                                </div>
                            </th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(is_array($this->usersList)): ?>
                        <?php foreach($this->usersList as $key => $val): ?>    
                        <tr>
                            <td class="text-center" style="width: 6%">
                                <a href="<?php echo BASE_URL . 'setting_users/delete_setting_users/' . $val['id_user'] . '/'; ?>" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userDelete']; ?>">
                                    <i class="icon <?php echo $val['icon_userDelete'];?>"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userType']; ?>">
                                    <i class="icon <?php echo $val['icon_userType'];?>"></i>
                                </a>
                            </td>
                            <td><?php echo $val['nick_name']; ?></td>
                            <td><?php echo $val['firstName']; ?></td>
                            <td><?php echo $val['lastName']; ?></td>
                            <td class="text-center">
                                <?php echo $val['status']; ?>
                            </td>
                            <td><?php echo $val['email']; ?></td>
                            <td class="text-center" style="width: 6%;">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready" data-toggle="tooltip" 
                                data-placement="bottom" 
                                data-original-title="<?php echo $val['tp_userWebsite']; ?>">
                                    <i class="icon <?php echo $val['icon_userWebsite'];?> icon-pointer"></i>
                                </a>
                            </td>
                            <td class="text-center" style="width: 6%;">
                                <a href="#" class="shortcut-button btn btn-icon mx-1 fuse-ripple-ready">
                                    <i class="icon icon-pencil"></i>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php endif; ?>
                        

                        
                    </tbody>
                </table>

                <script type="text/javascript">
                    $('#listusers-data-table').DataTable(
                    {
                        responsive: true,
                        dom         : 'rtip',

                        columnDefs  : [
                            { "orderable": false, "targets": 0 },
                            { "orderable": false, "targets": 1 },
                            { "orderable": false, "targets": 7 },
                            { "orderable": false, "targets": 8 },                  
                            {
                                targets   : 5,
                                filterable: false,
                                render    : function (data, type)
                                {
                                    if ( type === 'display' )
                                    {
                                        if ( data === 'A' )
                                        {
                                            return '<i class="icon-checkbox-marked-circle text-success"></i>';
                                        }

                                        return '<i class="icon-cancel text-danger"></i>';
                                    }

                                    if ( type === 'filter' )
                                    {
                                        if ( data )
                                        {
                                            return '1';
                                        }

                                        return '0';
                                    }

                                    return data;
                                }
                            },
                            {
                                // Target the actions column
                                targets           : 7,
                                responsivePriority: 1,
                                filterable        : false,
                                sortable          : false
                            }
                        ],
                        initComplete: function ()
                {
                    var api = this.api(),
                        searchBox = $('#products-search-input');

                    // Bind an external input as a table wide search box
                    if ( searchBox.length > 0 )
                    {
                        searchBox.on('keyup', function (event)
                        {
                            api.search(event.target.value).draw();
                        });
                    }
                },
                        lengthMenu  : [10, 20, 30, 50, 100],
                        pageLength  : 10,
                        scrollY     : 'auto',
                        scrollX     : false,
                        responsive  : true,
                        autoWidth   : false,
                        "aaSorting": [[ 4, "asc" ]],
                        "bDestroy": true
                    }
                );
                </script>

                </div></div>
      
            </div>
        </div>
    </div>
    </div>
</div>