<!DOCTYPE html>
<html lang="en">
    <head>     
        <meta charset="UTF-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>401</title>

        <!-- STYLESHEETS -->
        <style type="text/css">
            [fuse-cloak],
            .fuse-cloak {
                display: none !important;
            }
        </style>
        <!-- Icons.css -->
        <link type="text/css" rel="stylesheet" href="<?php echo $_layoutParams['root_css']; ?>icons/fuse-icon-font/style.css">
        <!-- Animate.css -->
        <link type="text/css" rel="stylesheet" href="<?php echo $_layoutParams['root_css']; ?>animate.css/animate.min.css">
        <!-- PNotify -->
        <link type="text/css" rel="stylesheet" href="<?php echo $_layoutParams['root_css']; ?>pnotify/pnotify.custom.min.css">
        <!-- Fuse Html -->
        <link type="text/css" rel="stylesheet" href="<?php echo $_layoutParams['root_css']; ?>fuse-html/fuse-html.min.css"/>
        <!-- Main CSS -->
        <link type="text/css" rel="stylesheet" href="<?php echo $_layoutParams['root_css']; ?>main.css">
        <!-- / STYLESHEETS -->
    </head>
    <body class="layout layout-vertical layout-left-navigation layout-below-toolbar">
      <div id="wrapper">
        <div class="content-wrapper">
        <div class="content">
          <div id="error-404" class="d-flex flex-column align-items-center justify-content-center">
            <div class="content">
              <div class="error-code display-1 text-center">401</div>
                <div class="message h4 text-center text-muted"><?php if($this->message) echo $this->message; ?></div>
                  <?php if(!Session::get('authentication')): ?>
                    <a href="<?php echo BASE_URL . 'login'; ?>" class="back-btn"><i class="fa fa-home"></i> Back To Home</a>
                  <?php endif; ?>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>
</html>