<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>500</title>

    
    <link href="<?php echo $_layoutParams['root_css']; ?>bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $_layoutParams['root_css']; ?>bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
   <!-- <link href="<?php echo $_layoutParams['root_css']; ?>font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
   <!-- <link href="<?php echo $_layoutParams['root_css']; ?>style.css" rel="stylesheet">
    <link href="<?php echo $_layoutParams['root_css']; ?>style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
<!--</head>
  <body class="body-404">
    <div class="error-head"> </div>
    <div class="container ">
      <section class="error-wrapper text-center">
          <h1><img src="<?php echo $_layoutParams['root_img']; ?>404.png" alt=""></h1>
          <div class="error-desk">
              <h2>page not found</h2>
              <p class="nrml-txt">We Couldn't Find This Page</p>
          </div>
           <?php if(!Session::get('authentication')): ?>
            <a href="<?php echo BASE_URL . 'login'; ?>" class="back-btn"><i class="fa fa-home"></i> Back To Home</a>
          <?php endif; ?>
      </section>
    </div>
  </body>
</html>-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Lock Screen</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $_layoutParams['root_css']; ?>bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $_layoutParams['root_css']; ?>bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="<?php echo $_layoutParams['root_css']; ?>font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="<?php echo $_layoutParams['root_css']; ?>style.css?1" rel="stylesheet">
    <link href="<?php echo $_layoutParams['root_css']; ?>style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="lock-screen" onload="startTime()">
    <div class="lock-wrapper">
        <div id="time"></div>
        <div class="lock-box text-center">
            <div class="lock-name">Jonathan Smith</div>
            <img src="images/lock_thumb.jpg" alt="lock avatar"/>
            <div class="lock-pwd">
                <form role="form" class="form-inline" action="index.html">
                    <div class="form-group">
                        <input type="password" placeholder="Password" id="exampleInputPassword2" class="form-control lock-input">
                        <button class="btn btn-lock" type="submit">
                            <i class="fa fa-arrow-right"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function startTime()
        {
            var today=new Date();
            var h=today.getHours();
            var m=today.getMinutes();
            var s=today.getSeconds();
            // add a zero in front of numbers<10
            m=checkTime(m);
            s=checkTime(s);
            document.getElementById('time').innerHTML=h+":"+m+":"+s;
            t=setTimeout(function(){startTime()},500);
        }

        function checkTime(i)
        {
            if (i<10)
            {
                i="0" + i;
            }
            return i;
        }
    </script>
</body>
</html>
